---
title: "Spring Legacies MS Analysis"
author: "Kathy Condon"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
library(knitr)
library(tidyverse)
library(dplyr)
library(car)
library(emmeans)
library(multcomp)
library(lmerTest)
library(lme4)
library(RColorBrewer)
library(rstatix)
library(tidyr)
library(ggpubr)
library(lubridate)
library(ggtext)
library(ggh4x)
library(ggpattern)
library(data.table)

plot_theme<-theme_classic()+
  theme(
    strip.background=element_blank(),
    strip.text.x=element_text(size=20,
                              hjust=0,
                              face="bold",colour="black"),
    strip.text.y=element_text(size=20,
                              hjust=0,
                              face="bold",colour="black"),
    panel.background=element_rect(fill="transparent"),
    panel.border=element_rect(fill="transparent",color="black",
                              linewidth=2),
    plot.background=element_rect(fill="transparent",color=NA),
    legend.background=element_rect(fill="transparent",
                                       linewidth=0.5),
    legend.position="none",
    # legend.title=element_text(size=30,face="bold"),
    legend.text=element_text(size=16),
    axis.line.x=element_line(linewidth=1,color="black"),
    axis.line.y=element_blank(),
    axis.ticks=element_line(linewidth=1,color="black"),
    axis.title = element_text(size=20,
                              colour="black",face="bold"),
    axis.text=element_text(size=16,colour="black"),
    axis.text.x=element_text(angle=45,hjust=1,colour="black"),
    axis.text.y=element_text(colour="black"),
    plot.title=element_text(size=20),
    strip.placement="outside")

```

### 1. VWC
```{r VWC data setup, include=FALSE}
# Read in data
vwc.dat<-read.csv("SGS_SLs_20cmVWC_all.csv")
str(vwc.dat) # 1220 observations

# Convert categorical columns
fact.cols<-c("Plot","NewTrt","Comb.TRT")

dat<-vwc.dat%>%
  mutate_at(fact.cols,factor)

str(dat)

# Convert data column
dat$new.Date<-as.Date(dat$Date,format="%m/%d/%y")

# Create Plot-Date ID's
dat$Unique_ID<-paste(dat$new.Date,
                         "Plot",
                         dat$Plot,
                         sep="_")

# Assign Deluge periods
dat<-dat%>%
  mutate(deluge_period=case_when(
    new.Date %within% interval ("2021-04-01","2021-06-23") ~ "pre.del",
    new.Date %within% interval ("2021-06-24","2021-07-15") ~ "nat.del.resp",
    new.Date %within% interval ("2021-07-16","2021-08-06") ~ "exp.del.resp",
    new.Date %within% interval ("2021-08-07","2021-09-30") ~ "post.del"))%>%
  select(new.Date,deluge_period,Plot,NewTrt,Comb.TRT,VWC,Unique_ID)%>%
  mutate(deluge_period=factor(deluge_period,levels=c("pre.del","nat.del.resp","exp.del.resp","post.del")))%>%
  mutate(NewTrt=factor(NewTrt,levels=c("amb","amb w/ deluge","dry w/ deluge")))%>%
  mutate(Comb.TRT=case_when(
    new.Date %within% interval ("2021-05-01","2021-07-15") & NewTrt %in% c("amb","amb w/ deluge") ~ "amb",
    new.Date %within% interval ("2021-05-01","2021-07-15") & NewTrt == "dry w/ deluge" ~ NewTrt,
    new.Date %within% interval ("2021-07-16","2021-09-30") ~ NewTrt))%>%
  mutate(month=months(new.Date))%>%
  mutate(month=factor(month,levels=c("May","June","July","August","September")))

str(dat) # 1220 observations

# Drop NA's
vwc.no.na<-dat%>%
  drop_na(VWC)

str(vwc.no.na) # 1208 observations

# From Bonferroni p-values (in other data file):
vwc.out.check2<-lmer(VWC~as.factor(new.Date)*NewTrt+(1|Plot),data=vwc.no.na)
outlierTest(vwc.out.check2,cutoff=0.05,n.max=Inf) # no different if using comb.TRT
vwc.outs<-vwc.no.na[c(42,461,701,517),]
vwc.sig.outs<-vwc.outs$Unique_ID
vwc.sig.outs # 4 significant outliers

# Drop outliers
vwc.no.out<-vwc.no.na%>%
  filter(! Unique_ID %in% vwc.sig.outs)%>%
  drop_na("VWC")

str(vwc.no.na) # 1208 observations
str(vwc.no.out) # 1204 observations
```

```{r VWC Stats}
# mod_dat<-vwc.no.na
mod_dat<-vwc.no.out
resp_var<-mod_dat$VWC

#### VWC line graph -- daily treatment differences ####
mod.og<-lmer(resp_var~NewTrt*as.factor(new.Date)+(1|Plot),data=mod_dat)
anova(mod.og,ddf="Kenward-Roger")
pairs(emmeans(mod.og,pairwise~NewTrt|new.Date))
cld(emmeans(mod.og,pairwise~NewTrt|new.Date),Letters=letters)

mod.og2<-lmer(resp_var~Comb.TRT*as.factor(new.Date)+(1|Plot),data=mod_dat)
anova(mod.og2,ddf="Kenward-Roger")
pairs(emmeans(mod.og2,pairwise~Comb.TRT|new.Date))
vwc.daily.letters<-cld(emmeans(mod.og2,pairwise~Comb.TRT|new.Date),Letters=letters)


#### VWC bars -- deluge periods ####
period.mod.log<-lmer(log(resp_var)~NewTrt*deluge_period+(1|Plot),data=mod_dat)
anova(period.mod.log,ddf="Kenward-Roger")
pairs(emmeans(period.mod.log,pairwise~NewTrt|deluge_period))
cld(emmeans(period.mod.log,pairwise~NewTrt|deluge_period),Letters=letters)

period.mod.log2<-lmer(log(resp_var)~Comb.TRT*deluge_period+(1|Plot),data=mod_dat)
anova(period.mod.log2,ddf="Kenward-Roger")
pairs(emmeans(period.mod.log2,pairwise~Comb.TRT|deluge_period))

# within
vwc.delperiod.letters<-cld(emmeans(period.mod.log2,pairwise~Comb.TRT|deluge_period),Letter=letters,decreasing=TRUE)

# across
# vwc.delperiod.letters<-cld(emmeans(period.mod.log2,~Comb.TRT*deluge_period),Letter=letters,decreasing=TRUE)


```

```{r VWC plots}
#### Daily line graph ####
vwc.daily.avs<-vwc.no.out%>%
  group_by(new.Date,Comb.TRT)%>%
  dplyr::summarise(
    n.plots=n(),
    av=mean(VWC),
    sd=sd(VWC),
    SE=sd/sqrt(n.plots))
vwc.daily.avs

gr_dat<-vwc.daily.avs
x.var=gr_dat$av
y.var=gr_dat$new.Date

vwc.plot<-ggplot(data=gr_dat,aes(x=x.var,y=y.var))+
  annotate("rect",xmin=as.Date("2021-06-24"),xmax=as.Date("2021-07-16"),ymin=-Inf,ymax=Inf,fill="gray90",alpha=1)+
  annotate("rect",xmin=as.Date("2021-07-16"),xmax=as.Date("2021-08-06"),ymin=-Inf,ymax=Inf,fill="gray75",alpha=1)+
  annotate("segment",x=as.Date("2021-07-15"),y=31.3,
           xend=as.Date("2021-07-17"),yend=47.1,
           colour="#3D5A80",linewidth=1.25)+
  geom_hline(yintercept=30,linewidth=1.25,color="gray20")+
  geom_line(data=subset(gr_dat,Comb.TRT=="amb"),
            aes(x=new.Date,y=av),
            linewidth=1.25,color="#98C1D9")+
  geom_errorbar(data=subset(gr_dat,Comb.TRT=="amb"),
                aes(x=new.Date,y=av,ymin=av-SE,ymax=av+SE),
                width=1,linewidth=1,color="#698696")+
  geom_point(data=subset(gr_dat,Comb.TRT=="amb"),
             aes(x=new.Date,y=av),
             pch=21,size=3.5,color="#698696",fill="#98C1D9",stroke=1.25)+
  geom_line(data=subset(gr_dat,Comb.TRT=="amb w/ deluge"),
            aes(x=new.Date,y=av),
            linewidth=1.25,color="#3D5A80")+
  geom_errorbar(data=subset(gr_dat,Comb.TRT=="amb w/ deluge"),
                aes(x=new.Date,y=av,ymin=av-SE,ymax=av+SE),
                width=1,linewidth=1,color="#1F2D40")+
  geom_point(data=subset(gr_dat,Comb.TRT=="amb w/ deluge"),
             aes(x=new.Date,y=av),
             pch=21,size=3.5,color="#1F2D40",fill="#3D5A80",stroke=1.25)+
  geom_line(data=subset(gr_dat,Comb.TRT=="dry w/ deluge"),
            aes(x=new.Date,y=av),
            linewidth=1.25,color="#EE6C4D")+
  geom_errorbar(data=subset(gr_dat,Comb.TRT=="dry w/ deluge"),
                aes(x=new.Date,y=av,ymin=av-SE,ymax=av+SE),
                width=1,linewidth=1,color="#AB4E37")+
  geom_point(data=subset(gr_dat,Comb.TRT=="dry w/ deluge"),
             aes(x=new.Date,y=av),
             pch=21,size=3.5,color="#AB4E37",fill="#EE6C4D",stroke=1.25)+
  scale_x_date(date_labels="%B",date_breaks="1 month",
               limits=as.Date(c("2021-05-02","2021-09-15")))+
  scale_y_continuous(expand=c(0,0))+
  coord_cartesian(ylim=c(0,51))+
  labs(title="",x="",y=expression(bold("0-20 cm Soil"[VWC]* " (%)")))+
  plot_theme+
  theme(legend.position="right",
        axis.text.x=element_text(angle=0,hjust=0.5))+
  force_panelsizes(rows = unit(4, "in"),
                   cols = unit(9, "in"))

vwc.plot

# ggsave(vwc.plot,filename="R1/MS_SGS_2021_VWC_lines.pdf",bg="transparent",width=11.5,height=5)

#### Deluge period bars ####
## Get averages and error bars
vwc.delperiod.avs<-vwc.no.out%>%
  group_by(deluge_period,Comb.TRT)%>%
  dplyr::summarise(
    n.plots=n(),
    av=mean(VWC),
    sd=sd(VWC),
    av.SE=sd/sqrt(n.plots))

vwc.delperiod.avs
vwc.delperiod.letters

## Combine emmeans significance 
vwc.monthly.plot<-merge(vwc.delperiod.avs,vwc.delperiod.letters,by=c("deluge_period","Comb.TRT"))

gr_dat<-vwc.monthly.plot%>%
  mutate(deluge_period=fct_relevel(deluge_period,c("pre.del","nat.del.resp","exp.del.resp","post.del")))%>%
  mutate(Comb.TRT=fct_relevel(Comb.TRT,c("amb","amb w/ deluge","dry w/ deluge")))%>%
  mutate(across(where(is.character), str_trim))

## Create plot
vwc.avs.del.periods<-ggplot(data=gr_dat,aes(x=deluge_period,y=av,fill=Comb.TRT,color=Comb.TRT))+
  annotate("rect",xmin=1.5,xmax=2.5,ymin=-Inf,ymax=Inf,fill="gray90",alpha=1)+
  annotate("rect",xmin=2.5,xmax=3.5,ymin=-Inf,ymax=Inf,fill="gray75",alpha=1)+
  geom_hline(yintercept=30,linewidth=1.25,color="gray20")+
  theme_classic()+
  geom_bar(position=position_dodge(0.75),stat="identity",width=0.65,linewidth=1)+
  geom_errorbar(aes(ymin=av-av.SE,ymax=av+av.SE),position=position_dodge(0.75),width=0,linewidth=1)+
  scale_fill_discrete(name="",labels=c("A","A+D","D+D"),type=c("#98c1d9","#3d5a80","#ee6c4d"))+
  scale_color_discrete(name="",labels=c("A","A+D","D+D"),type=c("#698696","#1f2d40","#ab4e37"))+
  labs(y=expression(bold("0-20 cm Soil"[VWC]* " (%)")),x="")+
  geom_text(aes(label=.group,y=av+av.SE+5),position=position_dodge(0.75),size=6.5,color="black")+
  scale_x_discrete(labels=c("Pre","Nat.\nResp.","Exp.\nResp.","Post"))+
  scale_y_continuous(expand=c(0,0))+
  coord_cartesian(ylim=c(0,51))+
  plot_theme+
  theme(
        # legend.position="inside",
        # legend.position.inside=c(0.9,0.9),
        legend.position="none",
        axis.text.x=element_text(angle=0,hjust=.5,colour="black"))+
  force_panelsizes(rows = unit(4, "in"),
                   cols = unit(4, "in"))

vwc.avs.del.periods

## Export plot
# ggsave(vwc.avs.del.periods,filename="R1/MS_SGS_2021_VWC_periodbars.pdf",bg="transparent",height=5,width=5)

```

### 2. GCC
```{r GCC data setup, include=FALSE}
# Read in data
gcc.dat<-read.csv("SGS_SLs_GCC_all.csv")
str(gcc.dat) # 960 observations

# Convert categorical columns
fact.cols<-c("Plot","Drop","NewTrt")
gcc.dat<-gcc.dat%>%
  mutate_at(fact.cols,factor)

# Convert date column
gcc.dat$new.Date<-as.Date(gcc.dat$Date,format="%m/%d/%y")

# Create Plot-Date ID's
gcc.dat$Unique_ID<-paste(gcc.dat$new.Date,
                         "Plot",
                         gcc.dat$Plot,
                         sep="_")

# Assign Deluge periods & Select data to keep
dat<-gcc.dat%>%
  filter(Drop=="n")%>%
  mutate(deluge_period=case_when(
    new.Date %within% interval ("2021-04-01","2021-06-23") ~ "pre.del",
    new.Date %within% interval ("2021-06-24","2021-07-15") ~ "nat.del.resp",
    new.Date %within% interval ("2021-07-16","2021-08-06") ~ "exp.del.resp",
    new.Date %within% interval ("2021-08-07","2021-09-30") ~ "post.del"))%>%
  select(new.Date,deluge_period,Plot,NewTrt,GCC,Unique_ID)%>%
  mutate(deluge_period=factor(deluge_period,levels=c("pre.del","nat.del.resp","exp.del.resp","post.del")))%>%
  mutate(Comb.TRT=case_when(
    new.Date %within% interval ("2021-04-01","2021-07-15") & NewTrt %in% c("amb","amb w/ deluge") ~ "amb",
    new.Date %within% interval ("2021-04-01","2021-07-15") & NewTrt == "dry w/ deluge" ~ "dry w/ deluge",
    new.Date %within% interval ("2021-07-16","2021-09-30") ~ NewTrt
  ))%>%
  mutate(NewTrt=factor(NewTrt,levels=c("amb","amb w/ deluge","dry w/ deluge")))%>%
  mutate(month=months(new.Date))%>%
  mutate(month=factor(month,levels=c("May","June","July","August","September")))

str(dat)

gcc.no.na<-dat%>%
  drop_na("GCC")

str(gcc.no.na)

### Bonferroni p-value significant outliers:
gcc.out.check<-lmer(GCC~as.factor(new.Date)*NewTrt+(1|Plot),data=gcc.no.na)
outlierTest(gcc.out.check,cutoff=0.05,n.max=Inf)
gcc.outs<-gcc.no.na[c(449,168,42,559,646,519,596,644),]
gcc.sig.outs<-gcc.outs$Unique_ID
gcc.sig.outs # 8 outliers 

gcc.no.out<-gcc.no.na%>%
  filter(!Unique_ID %in% gcc.sig.outs)

str(gcc.no.out) # 898 observations
```

```{r GCC Stats}
# mod_dat<-gcc.dat.no.na
mod_dat<-gcc.no.out
resp_var<-mod_dat$GCC

#### GCC line graph -- daily treatment differences ####
mod.og<-lmer(resp_var~NewTrt*as.factor(new.Date)+(1|Plot),data=mod_dat)
anova(mod.og,ddf="Kenward-Roger")
pairs(emmeans(mod.og,pairwise~NewTrt|new.Date))
cld(emmeans(mod.og,pairwise~NewTrt|new.Date),Letters=letters)

mod.og2<-lmer(resp_var~Comb.TRT*as.factor(new.Date)+(1|Plot),data=mod_dat)
anova(mod.og2,ddf="Kenward-Roger")
pairs(emmeans(mod.og2,pairwise~Comb.TRT|new.Date))
cld(emmeans(mod.og2,pairwise~Comb.TRT|new.Date),Letters=letters)


#### GCC bars -- deluge periods ####
period.mod.og<-lmer(resp_var~NewTrt*deluge_period+(1|Plot),data=mod_dat)
anova(period.mod.og,ddf="Kenward-Roger")
pairs(emmeans(period.mod.og,pairwise~NewTrt|deluge_period))
cld(emmeans(period.mod.og,pairwise~NewTrt|deluge_period),Letters=letters)

period.mod.og2<-lmer(resp_var~Comb.TRT*deluge_period+(1|Plot),data=mod_dat)
anova(period.mod.og2,ddf="Kenward-Roger")
pairs(emmeans(period.mod.og2,pairwise~Comb.TRT|deluge_period))

# within
gcc.delperiod.letters<-cld(emmeans(period.mod.og2,pairwise~Comb.TRT|deluge_period),Letters=letters,decreasing=TRUE)

# across
# gcc.delperiod.letters<-cld(emmeans(period.mod.og2,~Comb.TRT*deluge_period),Letters=letters,decreasing=TRUE)

```

```{r GCC plots}
#### Daily line graph ####
gcc.daily.avs<-gcc.no.out%>%
  group_by(new.Date,Comb.TRT)%>%
  dplyr::summarise(
    n.plots=n(),
    av=mean(GCC),
    sd=sd(GCC),
    SE=sd/sqrt(n.plots))
gcc.daily.avs

gr_dat<-gcc.daily.avs
x.var=gr_dat$av
y.var=gr_dat$new.Date

subset(gcc.daily.avs,gcc.daily.avs$new.Date %within% interval ("2021-07-12","2021-07-24"))

gcc.plot<-ggplot(data=gr_dat,aes(x=x.var,y=y.var))+
  annotate("rect",xmin=as.Date("2021-06-24"),xmax=as.Date("2021-07-16"),ymin=-Inf,ymax=Inf,fill="gray90",alpha=1)+
  annotate("rect",xmin=as.Date("2021-07-16"),xmax=as.Date("2021-08-06"),ymin=-Inf,ymax=Inf,fill="gray75",alpha=1)+
  annotate("segment",x=as.Date("2021-07-12"),y=0.376,
           xend=as.Date("2021-07-20"),yend=0.387,
           colour="#3D5A80",linewidth=1.25)+
  geom_line(data=subset(gr_dat,Comb.TRT=="amb"),
            aes(x=new.Date,y=av),
            linewidth=1.25,color="#98C1D9")+
  geom_errorbar(data=subset(gr_dat,Comb.TRT=="amb"),
                aes(x=new.Date,y=av,ymin=av-SE,ymax=av+SE),
                width=1,linewidth=1,color="#698696")+
  geom_point(data=subset(gr_dat,Comb.TRT=="amb"),
             aes(x=new.Date,y=av),
             pch=21,size=3.5,color="#698696",fill="#98C1D9",stroke=1.25)+
  geom_line(data=subset(gr_dat,Comb.TRT=="amb w/ deluge"),
            aes(x=new.Date,y=av),
            linewidth=1.25,color="#3D5A80")+
  geom_errorbar(data=subset(gr_dat,Comb.TRT=="amb w/ deluge"),
                aes(x=new.Date,y=av,ymin=av-SE,ymax=av+SE),
                width=1,linewidth=1,color="#1F2D40")+
  geom_point(data=subset(gr_dat,Comb.TRT=="amb w/ deluge"),
             aes(x=new.Date,y=av),
             pch=21,size=3.5,color="#1F2D40",fill="#3D5A80",stroke=1.25)+
  geom_line(data=subset(gr_dat,Comb.TRT=="dry w/ deluge"),
            aes(x=new.Date,y=av),
            linewidth=1.25,color="#EE6C4D")+
  geom_errorbar(data=subset(gr_dat,Comb.TRT=="dry w/ deluge"),
                aes(x=new.Date,y=av,ymin=av-SE,ymax=av+SE),
                width=1,linewidth=1,color="#AB4E37")+
  geom_point(data=subset(gr_dat,Comb.TRT=="dry w/ deluge"),
             aes(x=new.Date,y=av),
             pch=21,size=3.5,color="#AB4E37",fill="#EE6C4D",stroke=1.25)+
  scale_x_date(date_labels="%B",date_breaks="1 month",
               limits=as.Date(c("2021-05-02","2021-09-15")))+
  scale_y_continuous(expand=c(0,0))+
  coord_cartesian(ylim=c(0.33,0.403))+
  labs(title="",x="",y="Canopy Greenness (GCC)")+
  plot_theme+
  theme(legend.position="right",
        axis.text.x=element_text(angle=0,hjust=0.5))+
  force_panelsizes(rows = unit(4, "in"),
                   cols = unit(7, "in"))

gcc.plot

# ggsave(gcc.plot,filename="R1/MS_SGS_2021_GCC_lines.pdf",bg="transparent",width=11.5,height=5)


#### Deluge period bars ####
## Get averages and error bars
gcc.delperiod.avs<-gcc.no.out%>%
  group_by(deluge_period,Comb.TRT)%>%
  dplyr::summarise(
    n.plots=n(),
    av=mean(GCC),
    sd=sd(GCC),
    av.SE=sd/sqrt(n.plots))

gcc.delperiod.avs
gcc.delperiod.letters
  
## Combine emmeans significance
gcc.monthly.plot<-merge(gcc.delperiod.avs,gcc.delperiod.letters,by=c("deluge_period","Comb.TRT"))

gr_dat<-gcc.monthly.plot%>%
  mutate(deluge_period=fct_relevel(deluge_period,c("pre.del","nat.del.resp","exp.del.resp","post.del")))%>%
  mutate(Comb.TRT=fct_relevel(Comb.TRT,c("amb","amb w/ deluge","dry w/ deluge")))%>%
  mutate(across(where(is.character), str_trim))

## Create plot
gcc.avs.del.periods<-ggplot(data=gr_dat,aes(x=deluge_period,y=av,fill=Comb.TRT,color=Comb.TRT))+
  annotate("rect",xmin=1.5,xmax=2.5,ymin=-Inf,ymax=Inf,fill="gray90",alpha=1)+
  annotate("rect",xmin=2.5,xmax=3.5,ymin=-Inf,ymax=Inf,fill="gray75",alpha=1)+
  theme_classic()+
  geom_bar(position=position_dodge(0.75),stat="identity",width=0.65,linewidth=1)+
  geom_errorbar(aes(ymin=av-av.SE,ymax=av+av.SE),position=position_dodge(0.75),width=0,linewidth=1)+
  scale_fill_discrete(name="",labels=c("A","A+De","Dr+De"),type=c("#98c1d9","#3d5a80","#ee6c4d"))+
  scale_color_discrete(name="",labels=c("A","A+De","Dr+De"),type=c("#698696","#1f2d40","#ab4e37"))+
  labs(y="",x="")+
  geom_text(aes(label=.group,y=av+av.SE+0.005),position=position_dodge(0.75),size=5,color="black")+
  scale_x_discrete(labels=c("Pre","Nat.\nResp.","Exp. \nResp.","Post"))+
  scale_y_continuous(expand=c(0,0))+
  coord_cartesian(ylim=c(0.33,0.403))+
  plot_theme+
  theme(
        legend.position="inside",
        legend.position.inside=c(0.83,0.9),
        # legend.position="none",
        axis.text.x=element_text(angle=0,hjust=0.5,colour="black"))+
  force_panelsizes(rows = unit(4, "in"),
                   cols = unit(3.5, "in"))

gcc.avs.del.periods

## Export plot
# ggsave(gcc.avs.del.periods,filename="R1/MS_SGS_2021_GCC_periodbars.pdf",bg="transparent",width=5,height=5)
```

### 3. Efflux
```{r Respiration data setup, include=FALSE}
# Read in data 
resp.dat<-read.csv("SGS_SLs_Respiration_all.csv")
str(resp.dat) # 400 observations

# Convert categorical columns
fact.cols<-c("Plot","NewTrt")
resp.dat<-resp.dat%>%
  mutate_at(fact.cols,factor)

# Convert date column
resp.dat$new.Date<-as.Date(resp.dat$Date,format="%m/%d/%y")

# Create Plot-Date ID's
resp.dat$Unique_ID<-paste(resp.dat$new.Date,
                          "Plot",
                          resp.dat$Plot,
                          sep="_")

# Add time labels
resp<-resp.dat%>%
  mutate(deluge_period=case_when(
    new.Date %within% interval ("2021-04-01","2021-06-23") ~ "pre.del",
    new.Date %within% interval ("2021-06-24","2021-07-15") ~ "nat.del.resp",
    new.Date %within% interval ("2021-07-16","2021-08-06") ~ "exp.del.resp",
    new.Date %within% interval ("2021-08-07","2021-09-30") ~ "post.del"))%>%
  select(new.Date,deluge_period,Plot,NewTrt,Soil_Temp,Efflux,Unique_ID,Drop_resp,Drop_temp)%>%
  mutate(deluge_period=factor(deluge_period,levels=c("pre.del","nat.del.resp","exp.del.resp","post.del")))%>%
  mutate(NewTrt=factor(NewTrt,levels=c("amb","amb w/ deluge","dry w/ deluge")))%>%
  
  mutate(month=months(new.Date))%>%
  mutate(month=factor(month,levels=c("May","June","July","August","September")))%>%
  mutate(Comb.TRT=case_when(
    new.Date %within% interval ("2021-05-01","2021-07-15") & NewTrt %in% c("amb","amb w/ deluge") ~ "amb",
    new.Date %within% interval ("2021-05-01","2021-07-15") & NewTrt == "dry w/ deluge" ~ "dry w/ deluge",
    new.Date %within% interval ("2021-07-17","2021-09-30") ~ NewTrt))

str(resp)

# Drop NA's
resp.no.na<-resp%>%
  drop_na(Efflux)

temp.no.na<-resp%>%
  drop_na(Soil_Temp)

### Bonferroni p-values outliers:
resp.out.check<-lmer(Efflux~as.factor(new.Date)*NewTrt+(1|Plot),data=resp.no.na)
outlierTest(resp.out.check,cutoff=0.05,n.max=Inf) # 3 outliers
resp.outs<-resp.no.na[c(228,297,253),]
resp.sig.outs<-resp.outs$Unique_ID

resp.no.out<-resp.no.na%>%
  filter(!Unique_ID %in% resp.sig.outs)

temp.out.check<-lmer(Soil_Temp~as.factor(new.Date)*NewTrt+(1|Plot),data=temp.no.na)
outlierTest(temp.out.check,cutoff=0.05,n.max=Inf) # 1 outlier
temp.outs<-temp.no.na[c(231),]
temp.sig.outs<-temp.outs$Unique_ID

temp.no.out<-temp.no.na%>%
  filter(!Unique_ID %in% temp.sig.outs)
```

```{r Respiration Stats}
# mod_dat<-resp.no.na
mod_dat<-resp.no.out
resp_var<-mod_dat$Efflux

#### Efflux line graph -- daily treatment differences ####
mod.log<-lmer(log(resp_var)~NewTrt*as.factor(new.Date)+(1|Plot),data=mod_dat)
anova(mod.log,ddf="Kenward-Roger")
pairs(emmeans(mod.log,pairwise~NewTrt|new.Date))
cld(emmeans(mod.log,pairwise~NewTrt|new.Date),Letters=letters)

mod.log2<-lmer(log(resp_var)~Comb.TRT*as.factor(new.Date)+(1|Plot),data=mod_dat)
anova(mod.log2,ddf="Kenward-Roger")
pairs(emmeans(mod.log2,pairwise~Comb.TRT|new.Date))
cld(emmeans(mod.log2,pairwise~Comb.TRT|new.Date),Letters=letters)


#### Efflux bars -- deluge periods ####
period.mod.og<-lmer(resp_var~NewTrt*deluge_period+(1|Plot),data=mod_dat)
anova(period.mod.og,ddf="Kenward-Roger")
pairs(emmeans(period.mod.og,pairwise~NewTrt|deluge_period))
cld(emmeans(period.mod.og,pairwise~NewTrt|deluge_period),Letters=letters)

period.mod.og2<-lmer(resp_var~Comb.TRT*deluge_period+(1|Plot),data=mod_dat)
anova(period.mod.og2,ddf="Kenward-Roger")
pairs(emmeans(period.mod.og2,pairwise~Comb.TRT|deluge_period))

# within
efflux.delperiod.letters<-cld(emmeans(period.mod.og2,pairwise~Comb.TRT|deluge_period),Letters=letters)

# across
# efflux.delperiod.letters<-cld(emmeans(period.mod.og2,~Comb.TRT*deluge_period),Letters=letters)

```

```{r Efflux plots}
#### Daily line graph ####
efflux.daily.avs<-resp.no.out%>%
  group_by(new.Date,Comb.TRT)%>%
  dplyr::summarise(
    n.plots=n(),
    av=mean(Efflux),
    sd=sd(Efflux),
    SE=sd/sqrt(n.plots))
efflux.daily.avs

gr_dat<-efflux.daily.avs
x.var=gr_dat$av
y.var=gr_dat$new.Date

subset(gr_dat,gr_dat$new.Date %within% interval ("2021-07-10","2021-07-22"))

efflux.plot<-ggplot(data=gr_dat,aes(x=x.var,y=y.var))+
  annotate("rect",xmin=as.Date("2021-06-24"),xmax=as.Date("2021-07-16"),ymin=-Inf,ymax=Inf,fill="gray90",alpha=1)+
  annotate("rect",xmin=as.Date("2021-07-16"),xmax=as.Date("2021-08-06"),ymin=-Inf,ymax=Inf,fill="gray75",alpha=1)+
  annotate("segment",x=as.Date("2021-07-12"),y=4.96,
           xend=as.Date("2021-07-22"),yend=4.13,
           colour="#3D5A80",linewidth=1.25)+
  geom_line(data=subset(gr_dat,Comb.TRT=="amb"),
            aes(x=new.Date,y=av),
            linewidth=1.25,color="#98C1D9")+
  geom_errorbar(data=subset(gr_dat,Comb.TRT=="amb"),
                aes(x=new.Date,y=av,ymin=av-SE,ymax=av+SE),
                width=1,linewidth=1,color="#698696")+
  geom_point(data=subset(gr_dat,Comb.TRT=="amb"),
             aes(x=new.Date,y=av),
             pch=21,size=3.5,color="#698696",fill="#98C1D9",stroke=1.25)+
  geom_line(data=subset(gr_dat,Comb.TRT=="amb w/ deluge"),
            aes(x=new.Date,y=av),
            linewidth=1.25,color="#3D5A80")+
  geom_errorbar(data=subset(gr_dat,Comb.TRT=="amb w/ deluge"),
                aes(x=new.Date,y=av,ymin=av-SE,ymax=av+SE),
                width=1,linewidth=1,color="#1F2D40")+
  geom_point(data=subset(gr_dat,Comb.TRT=="amb w/ deluge"),
             aes(x=new.Date,y=av),
             pch=21,size=3.5,color="#1F2D40",fill="#3D5A80",stroke=1.25)+
  geom_line(data=subset(gr_dat,Comb.TRT=="dry w/ deluge"),
            aes(x=new.Date,y=av),
            linewidth=1.25,color="#EE6C4D")+
  geom_errorbar(data=subset(gr_dat,Comb.TRT=="dry w/ deluge"),
                aes(x=new.Date,y=av,ymin=av-SE,ymax=av+SE),
                width=1,linewidth=1,color="#AB4E37")+
  geom_point(data=subset(gr_dat,Comb.TRT=="dry w/ deluge"),
             aes(x=new.Date,y=av),
             pch=21,size=3.5,color="#AB4E37",fill="#EE6C4D",stroke=1.25)+
  scale_x_date(date_labels="%B",date_breaks="1 month",
               limits=as.Date(c("2021-05-02","2021-09-15")))+
  scale_y_continuous(expand=c(0,0))+
  coord_cartesian(ylim=c(0,6.05))+
  labs(title="",x="",y=expression(bold("Soil"[resp]* " (µmol CO"[2]*" m"^-2*"s"^-1*")")))+
  plot_theme+
  theme(legend.position="right",
        axis.text.x=element_text(angle=0,hjust=0.5))+
  force_panelsizes(rows = unit(4, "in"),
                   cols = unit(7, "in"))
  

efflux.plot

# ggsave(efflux.plot,filename="R1/MS_SGS_2021_Efflux_lines.pdf",bg="transparent",width=11.5,height=5)

#### Deluge period bars ####
## Get averages and error bars
efflux.delperiod.avs<-resp.no.out%>%
  group_by(deluge_period,Comb.TRT)%>%
  dplyr::summarise(
    n.plots=n(),
    av=mean(Efflux),
    sd=sd(Efflux),
    av.SE=sd/sqrt(n.plots))

efflux.delperiod.avs
efflux.delperiod.letters

## Combine emmeans significance 
efflux.monthly.plot<-merge(efflux.delperiod.avs,efflux.delperiod.letters,by=c("deluge_period","Comb.TRT"))

gr_dat<-efflux.monthly.plot%>%
  mutate(deluge_period=fct_relevel(deluge_period,c("pre.del","nat.del.resp","exp.del.resp","post.del")))%>%
  mutate(Comb.TRT=fct_relevel(Comb.TRT,c("amb","amb w/ deluge","dry w/ deluge")))%>%
  mutate(across(where(is.character), str_trim))

## Create plot
efflux.avs.del.periods<-ggplot(data=gr_dat,aes(x=deluge_period,y=av,fill=Comb.TRT,color=Comb.TRT))+
  annotate("rect",xmin=1.5,xmax=2.5,ymin=-Inf,ymax=Inf,fill="gray90",alpha=1)+
  annotate("rect",xmin=2.5,xmax=3.5,ymin=-Inf,ymax=Inf,fill="gray75",alpha=1)+
  theme_classic()+
  geom_bar(position=position_dodge(0.75),stat="identity",width=0.65,linewidth=1)+
  geom_errorbar(aes(ymin=av-av.SE,ymax=av+av.SE),position=position_dodge(0.75),width=0,linewidth=1)+
  scale_fill_discrete(name="",labels=c("A","A+De","Dr+De"),type=c("#98c1d9","#3d5a80","#ee6c4d"))+
  scale_color_discrete(name="",labels=c("A","A+De","Dr+De"),type=c("#698696","#1f2d40","#ab4e37"))+
  labs(y="",x="")+
  geom_text(aes(label=.group,y=av+av.SE+0.3),position=position_dodge(0.75),size=5,color="black")+
  scale_x_discrete(labels=c("Pre","Nat.\nResp.","Exp.\nResp.","Post"))+
  coord_cartesian(ylim=c(0,6.05))+
  scale_y_continuous(expand=c(0,0))+
  plot_theme+
  theme(
        # legend.position="inside",
        # legend.position.inside=c(0.9,0.9),
        legend.position="none",
        axis.text.x=element_text(angle=0,hjust=.5,colour="black"))+
  force_panelsizes(rows = unit(4, "in"),
                   cols = unit(3.5, "in"))

efflux.avs.del.periods

## Export plot
# ggsave(efflux.avs.del.periods,filename="R1/MS_SGS_2021_Efflux_periodbars.pdf",bg="transparent",width=4,height=5)
```


### 4. ANPP
```{r all ANPP data setup, include=FALSE}
## Read in and relabel data ##
anpp<-read.csv("SGS_SLs_ANPP_all.csv")
# str(anpp) # 160 observations

anpp[anpp=="clip"]<-"July"
anpp[anpp=="clip2"]<-"September"
anpp[anpp=="reclip"]<-"July-Sept"
anpp[anpp=="TOTAL"]<-"Total"

# Assign factors
fact.cols<-c("Plot","Clip_Type","TRT","Comb.TRT")

anpp.no.na<-anpp%>%
  drop_na("ANPP")%>%
  mutate_at(fact.cols,factor)

# str(anpp.no.na) # 160 observations (no NA's)

anpp.no.na$Unique_ID<-paste(anpp.no.na$Clip_Type,
                         "Plot",
                         anpp.no.na$Plot,
                         sep="_")

## Bonferroni outlier tests ##
#### July Alone ####
july.alone<-anpp.no.na%>%
  filter(Clip_Type == "July")
# str(july.alone)

## 1. total ANPP ##
july.out.check<-lm(ANPP~Comb.TRT,data=july.alone)
outlierTest(july.out.check,n.max=Inf,cutoff=0.05) # only row 1 outlier
july.outs<-july.alone[c(1),]
july.sig.outs<-july.outs$Unique_ID
july.sig.outs

july.out.check2<-lm(ANPP~TRT,data=july.alone)
outlierTest(july.out.check2,n.max=Inf,cutoff=0.05) # same as previous

july.no.out<-july.alone%>%
  filter(!Unique_ID %in% july.sig.outs)
# str(july.no.out)

#### Regrowth Alone ####
regrowth.alone<-anpp.no.na%>%
  filter(Clip_Type=="July-Sept")
# str(regrowth.alone) # 40 observations

## 1. total ANPP ##
regrowth.out.check<-lm(ANPP~TRT,data=regrowth.alone)
outlierTest(regrowth.out.check,cutoff=0.05,n.max=Inf) # only outlier line 13
regrowth.outs<-regrowth.alone[c(13),]
regrowth.sig.outs<-regrowth.outs$Unique_ID
regrowth.sig.outs

regrowth.no.out<-regrowth.alone%>%
  filter(!Unique_ID %in% regrowth.sig.outs)
# str(regrowth.no.out) # 39 observations


#### September Total ####
sept<-anpp.no.na%>%
  filter(Clip_Type == "September")
str(sept) # 40 observations

## 1. total ANPP ##
sept.totals.out.check<-lm(ANPP~TRT,data=sept)
outlierTest(sept.totals.out.check,cutoff=0.05,n.max=Inf) # only outlier line 2
sept.totals.outs<-sept[c(2),]
sept.totals.sig.outs<-sept.totals.outs$Unique_ID
sept.totals.sig.outs

sept.totals.no.out<-sept%>%
  filter(!Unique_ID %in% sept.totals.sig.outs)
str(sept.totals.no.out) # 39 observations

```

```{r Total ANPP Stats}
#### July ####
mod.dat<-july.no.out
log.mod<-lm(log(ANPP)~TRT,data=mod.dat)
Anova(log.mod,type=3)
summary(log.mod)
july.letters<-cld(emmeans(log.mod,pairwise~TRT),Letters=letters)

#### Regrowth ####
mod.dat<-regrowth.no.out
sqrt.mod<-lm(sqrt(ANPP)~TRT,data=mod.dat)
Anova(sqrt.mod,type=3)
pairs(emmeans(sqrt.mod,pairwise~TRT))
regrowth.letters<-cld(emmeans(sqrt.mod,pairwise~TRT),Letters=letters,decreasing=TRUE)
summary(sqrt.mod)


#### September Total ####
mod.dat<-sept.totals.no.out
mod<-lm(ANPP~TRT,data=mod.dat)
Anova(mod,type=3)
pairs(emmeans(mod,pairwise~TRT))
sept.letters<-cld(emmeans(mod,pairwise~TRT),Letters=letters,decreasing=TRUE)

```


```{r ANPP Plots}
head(anpp.no.na)

## Combine anpp data again w/o outliers
anpp.all<-rbind(july.no.out,regrowth.no.out,sept.totals.no.out)
str(anpp.all)

anpp.avs<-anpp.all%>%
  group_by(Clip_Type,Comb.TRT)%>%
  dplyr::summarise(
    n=n(),
    av=mean(ANPP),
    sd=sd(ANPP),
    SE=sd/sqrt(n),
    GROUP="ANPP")

## Turn on for Regrowth Plot
# gr_dat<-subset(anpp.avs,Clip_Type=="July-Sept")
# name="R1/MS_SGS_2021_Regrowth_ANPP_3trts.pdf"
# letters<-c("a","b","a")

## Turn on for Sept Plot
# gr_dat<-subset(anpp.avs,anpp.avs$Clip_Type=="September")
# name="R1/MS_SGS_2021_September_ANPP.pdf"
# letters<-c("ab","a","b")

anpp.plot<-ggplot(data=gr_dat,aes(x=Comb.TRT,y=av,fill=Comb.TRT,color=Comb.TRT))+
  geom_bar(position=position_dodge(0.75),
           stat="identity",
           width=0.85,linewidth=1)+
  geom_errorbar(aes(ymin=av-SE,ymax=av+SE),
                position=position_dodge(0.75),width=0,
                linewidth=1)+
  scale_fill_discrete(name="",
                      type=c("#98c1d9","#3d5a80","#ee6c4d"),
                      labels=c("A","A+De","Dr+De"))+
  scale_color_discrete(name="",
                       type=c("#698696","#1f2d40","#ab4e37"))+
  labs(y=expression(paste(bold("Aboveground biomass (g m"^-2*")"))),x="",
       # title="Mid to Late ANPP" # on for regrowth
       title="End of Season ANPP" # on for Sept
       )+
  scale_x_discrete(
    labels=c("A","A+De","Dr+De")
  )+
  scale_y_continuous(
    # limits=c(0,41), # on for regrowth
    limits=c(0,151), # on for Sept
    breaks=c(0,25,50,75,100,125,150), # on for Sept
    expand=c(0,0)
  )+
  plot_theme+
  geom_text(aes(label=letters,
                y=av+SE+7 # on for Sept
                # y=av+SE+1.5 # on for regrowth
                ),
            position=position_dodge(0.75),size=6.5,color="black")+
  theme(axis.ticks.x=element_blank(),
        axis.text.x=element_text(angle=0,hjust=0.5),
        title=element_text(face="bold"))+
  force_panelsizes(rows=unit(4,"in"),
                   cols=unit(3,"in"))

anpp.plot

ggsave(anpp.plot,filename=name,bg="transparent",width=5,height=5)
         
```

### 5. PRS N
```{r PRS data setup, include=FALSE}
# Read in data
prs.dat<-read.csv('SGS_SLs_PRS_NO3droppedlow.csv')
str(prs.dat)

# Assign UniqueID's
prs.dat$Unique_ID<-paste("Plot",
                         prs.dat$Plot,
                         prs.dat$Nutrient,
                         prs.dat$TRT,
                         sep="_")

```

```{r PRS Stats}
#### NO3.N ####
prs.no3<-prs.dat%>%
  filter(Nutrient %in% c("NO3.N"))%>%
  drop_na("rate")%>%
  mutate(TRT=factor(TRT,levels=c("amb","amb w/ deluge","drought w/ deluge")))

str(prs.no3)
mod.dat<-prs.no3
no3.out.check<-lm(rate~TRT,data=mod.dat)
outlierTest(no3.out.check,n.max=Inf,cutoff=0.05) # row 27 outlier
no3.outs<-prs.no3[c(27),]
no3.sig.outs<-no3.outs$Unique_ID
mod.dat<-prs.no3%>%
  filter(!Unique_ID %in% no3.sig.outs)

# Create models
log.mod<-lm(log(rate)~TRT,data=mod.dat)
Anova(log.mod,type=3)
pairs(emmeans(log.mod,pairwise~TRT))
NO3.letters<-cld(emmeans(log.mod,pairwise~TRT),Letters=letters)
```

```{r PRS NO3 Plot}
NO3.no.out<-prs.no3%>%
  filter(!Unique_ID %in% no3.sig.outs)

NO3.avs<-NO3.no.out%>%
  group_by(TRT)%>%
  dplyr::summarise(
    n=n(),
    av=mean(rate),
    sd=sd(rate),
    av.SE=sd/sqrt(n),
    GROUP="NO3.avs")

NO3.letters

NO3.dat<-merge(NO3.avs,NO3.letters,by=c("TRT"))

gr_dat<-NO3.dat%>%
  mutate(TRT=fct_relevel(TRT,c("amb","amb w/ deluge","drought w/ deluge")))%>%
  mutate(across(where(is.character), str_trim))
  

NO3.plot<-ggplot(data=gr_dat,aes(x=TRT,y=av,fill=TRT,color=TRT))+
  geom_bar(position=position_dodge(0.75),
           stat="identity",
           width=0.85,linewidth=1)+
  geom_errorbar(aes(ymin=av-av.SE,ymax=av+av.SE),
                position=position_dodge(0.75),width=0,
                linewidth=1)+
  scale_fill_discrete(name="",
                      type=c("#98c1d9","#3d5a80","#ee6c4d"),
                      labels=c("A","A+De","De+Dr")
                      )+
  scale_color_discrete(name="",
                       type=c("#698696","#1f2d40","#ab4e37"),
                       labels=c("A","A+De","De+Dr")
                       )+
  ylab(expression(bold(atop("PRS Probe Uptake of NO"[3],"(µg 10cm"^-2*" 2 month burial"^-1*")"))))+
  xlab("")+
  scale_x_discrete(labels=c("A","A+De","Dr+De"))+
  scale_y_continuous(
    limits=c(0,83),
    expand=c(0,0)
  )+
  geom_text(aes(label=.group,y=av+av.SE+3),position=position_dodge(0.75),size=7.5,color="black")+
  plot_theme+
  theme(axis.ticks.x=element_blank(),
        axis.text.x=element_text(angle=0,hjust=0.5),
        title=element_text(face="bold"),
        legend.position="none")+
  force_panelsizes(rows=unit(4,"in"),
                   cols=unit(3,"in"))

NO3.plot

# ggsave(NO3.plot,filename="SGS_2021_MS_NO3.pdf",bg="transparent",width=5,height=5)

```


### 6. Sentek
```{r Sentek, include=TRUE}
#### Sentek data ####
sentek.dat<-read.csv("SGS_SLs_2021_Interpolated_Sentek_VWC.csv")
str(sentek.dat) # 28,160 observations

sentek.dat$Date<-as.Date(sentek.dat$doy, origin = "2021-01-01")

str(sentek.dat) # 28,160 observations

sentek.out.check<-lmer(VWC~depth*Trt+(1|Plot),data=sentek.dat)
outlierTest(sentek.out.check,cutoff=0.05,n.max=Inf) # Bonferroni p = NA, no outliers

sentek.dat$week<-lubridate::isoweek(sentek.dat$Date)

sentek.dat<-sentek.dat%>%
  mutate(deluge_period=case_when(
    Date %within% interval ("2021-05-02","2021-06-24") ~ "pre.del",
    Date %within% interval ("2021-06-25","2021-07-14") ~ "nat.del",
    Date %within% interval ("2021-07-15","2021-08-06") ~ "del.response",
    Date %within% interval ("2021-08-07","2021-09-30") ~ "post.del"))%>%
  mutate(deluge_period=factor(deluge_period,
                                 levels=c("pre.del","nat.del","del.response","post.del")))%>%
  mutate(TRT=factor(Trt,levels=c("amb","amb w/ deluge","dry w/ deluge")))%>%
  mutate(Comb.TRT=case_when(
    Date %within% interval ("2021-05-01","2021-07-15") & Trt %in% c("amb","amb w/ deluge") ~ "amb",
    Date %within% interval ("2021-05-01","2021-07-15") & Trt == "dry w/ deluge" ~ "dry w/ deluge",
    Date %within% interval ("2021-07-16","2021-09-30") ~ Trt))
  
sentek.deep<-sentek.dat%>%
  filter(depth > 70)%>%
  group_by(Plot,depth,TRT)%>%
  dplyr::summarise(
    n=n(),
    av=mean(VWC)
  )

#### Sentek by periods and depths ####
sentek.25<-sentek.dat%>%
  filter(between(depth,0,25))%>%
  group_by(TRT,deluge_period)%>%
  dplyr::summarise(
    n=n(),
    av=mean(VWC),
    sd=sd(VWC),
    SE=sd/sqrt(n),
    av.date=mean(Date),
    depth="0-25")

sentek.50<-sentek.dat%>%
  filter(between(depth,0,50))%>%
  group_by(TRT,deluge_period)%>%
  dplyr::summarise(
    n=n(),
    av=mean(VWC),
    sd=sd(VWC),
    SE=sd/sqrt(n),
    av.date=mean(Date),
    depth="0-50")
```

```{r Sentek stats}
#### Sentek 0-50cm ####
mod_dat<-sentek.dat%>%
  filter(depth %in% c(0:50))%>%
  group_by(Date,Trt,Comb.TRT,deluge_period,Plot)%>%
  dplyr::summarise(
    n.obs=n(),
    VWC.av=mean(VWC),
    VWC.sd=sd(VWC),
    VWC.SE=VWC.sd/sqrt(n.obs))

resp_var<-mod_dat$VWC.av
str(mod_dat)

mod<-lmer(resp_var~Trt*deluge_period+(1|Plot),data=mod_dat)
anova(mod,ddf="Kenward-Roger") 
pairs(emmeans(mod,pairwise~Trt|deluge_period))
cld(emmeans(mod,pairwise~Trt|deluge_period),Letters=letters)

mod2<-lmer(resp_var~Comb.TRT*deluge_period+(1|Plot),data=mod_dat)
anova(mod2,ddf="Kenward-Roger") 
pairs(emmeans(mod2,pairwise~Comb.TRT|deluge_period))

# within
sentek.delperiod.letters<-cld(emmeans(mod2,pairwise~Comb.TRT|deluge_period),Letters=letters,decreasing=TRUE)

# across
# sentek.delperiod.letters<-cld(emmeans(mod2,~Comb.TRT*deluge_period),Letters=letters,decreasing=TRUE)

```

```{r Sentek plots}
#### Deluge period bars ####
sentek.50.avs<-mod_dat%>%
  group_by(Comb.TRT,deluge_period)%>%
  dplyr::summarise(
    n.plots=n(),
    av=mean(VWC.av),
    sd=sd(VWC.av),
    av.SE=sd/sqrt(n.plots))

sentek.50.avs
sentek.delperiod.letters

sentek.periods.plot<-merge(sentek.50.avs,sentek.delperiod.letters,by=c("deluge_period","Comb.TRT"))

gr_dat<-sentek.periods.plot%>%
  mutate(deluge_period=fct_relevel(deluge_period,c("pre.del","nat.del","del.response","post.del")))%>%
  mutate(Comb.TRT=fct_relevel(Comb.TRT,c("amb","amb w/ deluge","dry w/ deluge")))%>%
  mutate(across(where(is.character), str_trim))

## Create plot
sentek.avs.del.periods<-ggplot(data=gr_dat,aes(x=deluge_period,y=av,fill=Comb.TRT,color=Comb.TRT))+
  annotate("rect",xmin=1.5,xmax=2.5,ymin=-Inf,ymax=Inf,fill="gray90",alpha=1)+
  annotate("rect",xmin=2.5,xmax=3.5,ymin=-Inf,ymax=Inf,fill="gray75",alpha=1)+
  geom_hline(yintercept=30,linewidth=1.25,color="gray20")+
  theme_classic()+
  geom_bar(position=position_dodge(0.75),stat="identity",width=0.65,linewidth=1)+
  geom_errorbar(aes(ymin=av-av.SE,ymax=av+av.SE),position=position_dodge(0.75),width=0,linewidth=1)+
  scale_fill_discrete(name="",labels=c("A","A+De","Dr+De"),type=c("#98c1d9","#3d5a80","#ee6c4d"))+
  scale_color_discrete(name="",labels=c("A","A+De","Dr+De"),type=c("#698696","#1f2d40","#ab4e37"))+
  labs(y=expression(bold("0-50 cm Soil"[VWC]* " (%)")),x="")+
  geom_text(aes(label=.group,y=av+av.SE+5),position=position_dodge(0.75),size=6.5,color="black")+
  scale_x_discrete(labels=c("Pre","Nat.\nResp.","Exp. \nResp.","Post"))+
  scale_y_continuous(expand=c(0,0))+
  coord_cartesian(ylim=c(0,51))+
  plot_theme+
  theme(
        legend.position="inside",
        legend.position.inside=c(0.83,0.9),
        axis.text.x=element_text(angle=0,hjust=0.5,colour="black"))+
  force_panelsizes(rows = unit(4, "in"),
                   cols = unit(4, "in"))

sentek.avs.del.periods

## Export plot
# ggsave(sentek.avs.del.periods,filename="R1/MS_SGS_2021_Sentek_periodbars.pdf",bg="transparent",width=5,height=5)


#### Sentek Heatmaps ####
## Treatment means 
allsm.trts.1<-sentek.dat%>%
  group_by(Trt, Date, depth)%>%
  mutate(Trt=factor(Trt,levels=c("amb","amb w/ deluge","dry w/ deluge")))%>%
  summarise(mean_vwc=mean(VWC, na.rm=TRUE))

head(allsm.trts.1)

# relabel levels of Trt factor
levels(allsm.trts.1$Trt)
levels(allsm.trts.1$Trt)<-c("A","A+De","Dr+De")

## Plot heatmap - trt means 
sentek_avs<-ggplot(allsm.trts.1, aes(Date, depth)) +
  geom_raster(aes(fill = mean_vwc), interpolate = TRUE)+
  scale_fill_gradientn(limits=c(0,60),colours = rainbow(9))+
  theme_classic()+
  ylab("Depth (cm)") +
  xlab("") +
  theme_classic()+
  plot_theme+
  theme(legend.position="right") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(colour = "black",
                                        linewidth=2),
        axis.line=element_blank(),
        legend.title = element_text(size = 16,face="bold"),
        legend.text = element_text(size = 14),
        strip.text.x=element_text(hjust=0))+
  labs(fill = expression(bold("Soil"[VWC]* " (%)")))+
  scale_y_reverse(breaks=c(25,50,75),
                  expand=c(0.05,0.05),
                  limits=c(80,10)
                  )+
  facet_wrap(~Trt)


sentek_avs

## Export heatmap by trts 
# ggsave(sentek_avs,filename="R1/MS_SGS_2021_sentek_heatmap.pdf",width=10,height=3.5)
```

### 7. Precipitation
```{r Precipitation Data}
#### Daily precip data ####
daily.precip<-read.csv("SGS_Precip_Combined.csv")

daily.precip<-daily.precip%>%
  mutate(new.Date=as.Date(new.Date,format="%m/%d/%y"))%>%
  mutate(ymd.date=ymd(new.Date))%>%
  group_by(yr=year(ymd.date),mon=month(ymd.date))

## Daily to monthly
daily.to.monthly<-daily.precip%>%
  filter(yr %in% c(1990:2024))%>%
  group_by(yr,mon)%>%
  dplyr::summarise(
    n.days=n(),
    noaa_LTA=sum(NOAA_mm2),
    usda_annual=sum(usda_20to21))%>%
  mutate(mon=as.character(mon))

str(daily.to.monthly)

monthly<-daily.to.monthly%>%
  mutate(mon=factor(mon,levels=c("1","2","3","4","5","6","7","8","9","10","11","12")))%>%
  mutate(USDA_20=case_when(yr == 2020 ~ usda_annual))%>%
  mutate(USDA_21=case_when(yr == 2021 ~ usda_annual))

str(monthly)

#### Averages ####
origin.df<-data.frame(
  data=c("web_mm","noaa_LTA","USDA_20","USDA_21"),
  mon=0,
  csum=0)%>%
  mutate(mon=factor(mon))

monthly.avs<-monthly%>%
  pivot_longer(cols=c("noaa_LTA","USDA_20","USDA_21"),names_to="data",values_to="precip_mm")%>%
  group_by(data,mon)%>%
  drop_na("precip_mm")%>%
  dplyr::summarise(
    n.yrs=n(),
    monthly.av=mean(precip_mm),
    monthly.sd=sd(precip_mm),
    monthly.SE=monthly.sd/sqrt(n.yrs))%>%
  mutate(data=factor(data))%>%
  mutate(csum=cumsum(monthly.av))%>%
  mutate(data=fct_relevel(data,"noaa_LTA","USDA_20","USDA_21"))

# view(monthly.avs)

monthly.avs.merge<-bind_rows(origin.df,monthly.avs,)

#### Daily GS ####
gs.all.yrs<-daily.precip%>%
  mutate(ymd.date=ymd(new.Date))%>%
  group_by(year=year(ymd.date),mon=month(ymd.date))%>%
  filter(ymd.date %within%
           interval (ymd(paste(first(year),
                               "04-01",
                               sep="-")),
                     ymd(paste(first(year),
                               "09-15",
                               sep="-"))))%>%
  summarise(
    NOAA_gs=sum(NOAA_mm2),
    USDA_gs=sum(usda_20to21))%>%
  pivot_longer(cols=c("NOAA_gs","USDA_gs"),names_to="data",values_to="mm")%>%
  drop_na("mm")%>%
  mutate(groups=case_when(
    year == 2021 & data == "USDA_gs" ~ "USDA_21",
    year == 2020 & data == "USDA_gs" ~ "USDA_20",
    TRUE ~ data))

# view(gs.all.yrs)

gs.avs<-gs.all.yrs%>%
  group_by(groups,mon)%>%
  dplyr::summarise(
    n=n(),
    gs.av=mean(mm),
    gs.sd=sd(mm),
    gs.SE=gs.sd/sqrt(n))%>%
  mutate(csum=cumsum(gs.av))%>%
  rename(data=groups)%>%
  mutate(data=factor(data,levels=c("NOAA_gs","USDA_20","USDA_21")))%>%
  mutate(mon=factor(mon))

gs.avs.merge<-bind_rows(origin.df,gs.avs)

```

```{r precip plotting}
#### Plotting monthly bars & cumu line ####
gr_dat<-monthly.avs%>%
  filter(!is.na(mon))%>%
  filter(data %in% c("noaa_LTA","USDA_21"))%>%
  rename(col=data)

monthly.precip.bars<-ggplot(data=gr_dat,color=col,group=col)+
  geom_line(data=gr_dat,
            aes(x=mon,
                y=csum,
                color=col,
                group=col,
                linetype=col),
            linewidth=0.75,
            inherit.aes=FALSE)+
  scale_linetype_manual(name="",
                          values=c("dashed","solid"),
                          labels=c("35-yr average","2021"))+
  geom_bar(aes(x=mon,y=monthly.av,fill=col,color=col),
           position=position_dodge(0.75),
           stat="identity",
           width=0.75,linewidth=0.75)+
  geom_errorbar(aes(x=mon,color=col,ymin=monthly.av-monthly.SE,ymax=monthly.av+monthly.SE),
                position=position_dodge(0.75),width=0,
                linewidth=0.75)+
  scale_fill_discrete(name="",
                      type=c("gray70","#98c1d9"),
                      # type=c("#3d5a80","#ee6c4d"),
                      # type=c("#98c1d9","#3d5a80","#ee6c4d"),
                      # labels=c("A","D"),
                      labels=c("35-yr average","2021"),
                      # labels=c("A","A+D","D+D")
                      )+
  scale_color_discrete(name="",
                       type=c("gray30","#698696"),
                       # type=c("#1f2d40","#ab4e37")
                       # type=c("#698696","#1f2d40","#ab4e37"),
                       labels=c("35-yr average","2021")
                       )+
  labs(y=expression(paste(bold("Precipitation (mm)"))),x="Date")+
  scale_x_discrete(labels=c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"),expand=c(0,0))+
  scale_y_continuous(
    limits=c(0,415),
    expand=c(0,0)
  )+
  plot_theme+
  theme(axis.ticks.x=element_blank(),
        axis.text.x=element_text(angle=0,hjust=0.5),
        legend.position="inside",
        legend.position.inside=c(0.14,0.9),
        title=element_text(face="bold"))+
  force_panelsizes(rows=unit(4,"in"),
                   cols=unit(8,"in"))

monthly.precip.bars

# ggsave(monthly.precip.bars,filename="R1/MS_2021_Fig1_Precip_bars.pdf",bg="transparent",width=9,height=5)

#### precip deluge distributions ####
precip_20plus<-daily.precip%>%
  mutate(ymd.date=ymd(new.Date))%>%
  filter(yr %in% c(1990:2024))%>%
  group_by(year=year(ymd.date),mon=month(ymd.date))%>%
  filter(ymd.date %within%
           interval (ymd(paste(first(year),
                               "04-01",
                               sep="-")),
                     ymd(paste(first(year),
                               "09-15",
                               sep="-"))))%>%
  mutate(event_size = case_when(
    yr %in% c(1990:2019) ~ NOAA_mm2,
    yr %in% c(2020:2021) ~ usda_20to21,
    yr %in% c(2022:2024) ~ NOAA_mm2))%>%
  mutate(rel_events = case_when(
    event_size <= 2 ~ 0,
    event_size > 2 ~ event_size))

gr_dat<-precip_20plus%>%
  ungroup()%>%
  mutate(group=rleid(rel_events > 0))%>%
  group_by(group)%>%
  summarise(n.days=n(),
            start_date=min(new.Date),
            end_date=max(new.Date),
            total_precip=sum(rel_events))%>%
  filter(total_precip>0)%>%
  filter(total_precip>20)

# view(gr_dat)

hist<-ggplot(aes(x=total_precip),data=gr_dat)+
  geom_histogram(binwidth=10,fill="gray70",color="gray30",
                 linewidth=0.75)+
  labs(y="# Events",x="Event size (mm)",title="")+
  theme_classic()+
  plot_theme+
  theme(axis.ticks.x=element_blank(),
        axis.text.x=element_text(angle=0,hjust=0.5),
        legend.position="inside",
        legend.position.inside=c(0.1,0.9),
        title=element_text(face="bold"))+
  scale_x_continuous(expand=c(0.05,0.05),
                     breaks=c(0,20,40,60,80,100,120))+
  scale_y_continuous(limits=c(0,36),
                     breaks=c(0,5,10,15,20,25,30,35),
                     expand=c(0,0))+
  force_panelsizes(rows=unit(4,"in"),
                   cols=unit(4.5,"in"))

hist

# ggsave(hist,filename="R1/MS_2021_Fig1_Deluge_hist.pdf",bg="transparent",width=5.5,height=5)

#### calc percentiles ####
quant.dat<-daily.precip%>%
  mutate(ymd.date=ymd(new.Date))%>%
  group_by(year=year(ymd.date),mon=month(ymd.date))%>%
  filter(ymd.date %within%
           interval (ymd(paste(first(year),
                               "04-01",
                               sep="-")),
                     ymd(paste(first(year),
                               "09-15",
                               sep="-"))))%>%
  mutate(event_size = case_when(
    yr %in% c(1990:2019) ~ NOAA_mm2,
    yr %in% c(2020:2021) ~ usda_20to21,
    yr %in% c(2022:2024) ~ NOAA_mm2))%>%
  filter(event_size>=2)

vals<-ecdf(quant.dat$event_size)
vals(60)

quant.dat<-quant.dat%>%
  mutate(event_quant=vals(event_size))

quantile(quant.dat$event_size,c(.25,.5,.75,.98,.99))

```








